### ISSUE TITLE
Custom Db Connect by importing db or schemas.

### ISSUE THREAD

**Issue by anujkumar10** [ujjwalguptaofficial/idbstudio#5]
Can we also open our application db created through JSStore v3 in idbstudio and run queries over it?

**Comment by ujjwalguptaofficial** [comment]
yes you can. For this you will have to install idbstudio locall & then you have two options - 

* Mount idbstudio at your project -  `idbstudio --generate` 
* Close your app & then start idbstudio at same port - `idbstudio --generate`

Second option is not recommended as you will have to stop your app.

**Comment by kinhoon** [comment]
Hi, 

I tried the following steps to connect to my application database, but the dropdown list does not show my database.
- Generate idbstudio with `idbstudio --generate`
- Copy the whole folder to my project
- Run my project with `npm run serve`

My server then runs and I am able to open the idbstudio startup page `http://localhost:8080/idbstudio/index.html`.
However, there is always only 1 option under the database dropdown, which is `Demo`.

I tried the `GET LINK` button, copied the URL and replace the db name to the following, but still unable to connect to my application database.
`http://localhost:8080/idbstudio/index.html?db=localhost:1884/demo9&query=`

Am I still missing some steps?

![image](https://user-images.githubusercontent.com/46112444/131220431-f9e3449a-8bec-492a-86ca-c1d752602d4d.png)

Thanks.

**Comment by ujjwalguptaofficial** [comment]
@kinhoon you are using v3 of jsstore, so please install v - 1.8.8 of idbstudio.

Latest version support v4 of jsstore

**Comment by kinhoon** [comment]
My app is using `jsstore@4.2.6` and running `npm -v idbstudio` shows version `6.14.12`. Is there any other way to check the version of idbstudio I am using? The version number is very different from the one you stated --> `1.8.8`.

Note that I install `idbstudio` globally using `npm i idbstudio -g`, and generate the idbstudio files using `idbstudio --generate`.
Seems I already have everything latest version?

**Comment by kinhoon** [comment]
Finally managed to get it. I need to:
- clone `idbstudio` repo from github, the version is `1.10.0`
- uninstall the existing old `idbstudio` version `1.8.7` with `npm uninstall idbstudio -g`
- install the latest version from folder with `npm install ./idbstudio-master -g`
- generate files with `idbstudio -g`
- copy the whole `idbstudio` folder generated to my project
- `npm run serve`, open browser, navigate to the path, then viola, I got it

Thanks
